python run_recbole.py -m=CDAE -d=ml-100k
python run_recbole.py -m=ConvNCF -d=ml-100k
python run_recbole.py -m=DGCF -d=ml-100k
python run_recbole.py -m=DMF -d=ml-100k
python run_recbole.py -m=EASE -d=ml-100k
python run_recbole.py -m=ENMF -d=ml-100k
python run_recbole.py -m=FISM -d=ml-100k
python run_recbole.py -m=GCMC -d=ml-100k
python run_recbole.py -m=ItemKNN -d=ml-100k
python run_recbole.py -m=LINE -d=ml-100k
python run_recbole.py -m=MacridVAE -d=ml-100k
python run_recbole.py -m=MultiDAE -d=ml-100k
python run_recbole.py -m=MultiVAE -d=ml-100k
python run_recbole.py -m=ENMF -d=ml-100k
python run_recbole.py -m=NAIS -d=ml-100k
python run_recbole.py -m=NCL -d=ml-100k
python run_recbole.py -m=NeuMF -d=ml-100k
python run_recbole.py -m=NGCF -d=ml-100k
python run_recbole.py -m=NNCF -d=ml-100k
python run_recbole.py -m=Pop -d=ml-100k
python run_recbole.py -m=RaCT -d=ml-100k
python run_recbole.py -m=RecVAE -d=ml-100k
python run_recbole.py -m=SLIMElastic -d=ml-100k
python run_recbole.py -m=SpectralCF -d=ml-100k
python run_recbole.py -m=NCEPLRec -d=ml-100k
python run_recbole.py -m=SGL -d=ml-100k
python run_recbole.py -m=ADMMSLIM -d=ml-100k
python run_recbole.py -m=SimpleX -d=ml-100k
python run_recbole.py -m=LightGCN -d=Custom_ml-100k_1