python run_recbole.py -m=BERT4Rec -d=ml-100k
python run_recbole.py -m=Caser -d=ml-100k
python run_recbole.py -m=CORE -d=ml-100k
python run_recbole.py -m=DIEN -d=ml-100k
python run_recbole.py -m=DIN -d=ml-100k
python run_recbole.py -m=FDSA -d=ml-100k
python run_recbole.py -m=FOSSIL -d=ml-100k
python run_recbole.py -m=FPMC -d=ml-100k
python run_recbole.py -m=GCSAN -d=ml-100k
python run_recbole.py -m=GRU4Rec -d=ml-100k
python run_recbole.py -m=GRU4RecF -d=ml-100k
python run_recbole.py -m=GRU4RecKG -d=ml-100k
python run_recbole.py -m=HGN -d=ml-100k
python run_recbole.py -m=HRM -d=ml-100k
python run_recbole.py -m=KSR -d=ml-100k
python run_recbole.py -m=LightSANs -d=ml-100k
python run_recbole.py -m=NARM -d=ml-100k
python run_recbole.py -m=NextItNet -d=ml-100k
python run_recbole.py -m=RepeatNet -d=ml-100k
python run_recbole.py -m=S3Rec -d=ml-100k
python run_recbole.py -m=SASRec -d=ml-100k
python run_recbole.py -m=SASRecF -d=ml-100k
python run_recbole.py -m=SHAN -d=ml-100k
python run_recbole.py -m=SINE -d=ml-100k
python run_recbole.py -m=SRGNN -d=ml-100k
python run_recbole.py -m=STAMP -d=ml-100k
python run_recbole.py -m=TransRec -d=ml-100k
python run_recbole.py -m=TAGNN -d=ml-100k